'use client';

import { auditSummary } from '@/lib/core/audit';
import { primitiveSummary } from '@/lib/core/primitives';
import { registry } from './catalog';
import { Header, NavRail, type NavGroup } from './Chrome';
import { ComponentIndex } from './ComponentIndex';
import { ThemeProvider } from './ThemeProvider';
import { Assembled } from '@/components/sections/Assembled';
import { Elevation } from '@/components/sections/Elevation';
import { Foundations } from '@/components/sections/Foundations';
import { Primitives } from '@/components/sections/Primitives';
import { Spectrum } from '@/components/sections/Spectrum';
import { Typography } from '@/components/sections/Typography';

/* ---------------------------------------------------------------------------
 * The page.
 *
 * Note what is not here: a list of components. The component sections and their nav
 * entries both come from `registry.all`, which is populated by catalog.tsx. Adding a
 * component is a recipe, a React component and one registration — this file does not
 * change.
 * ------------------------------------------------------------------------- */

/* Primitives first: the semantic section is built out of it, and reading the ramps
 * before the roles is the order that makes the roles make sense. */
const FOUNDATION_SECTIONS = [
  { id: 'primitives', label: 'Primitives' },
  { id: 'colour', label: 'Colour' },
  { id: 'typography', label: 'Typography' },
  { id: 'elevation', label: 'Elevation & motion' },
  { id: 'spectrum', label: 'Charts & gradients' },
];

/* The first screen of a page that ships publicly to people deciding whether to trust
 * this system, so it is allowed to be the loudest thing here — and it was not. The
 * headline sat at display-sm while display-md and display-lg went unused, which put
 * the whole page inside two steps of a fifteen-step scale.
 *
 * The five figures are the argument, so they are set at display-sm — the size the
 * headline used to be — rather than heading-md. Their labels keep the uppercase mono
 * treatment that was dropped elsewhere: it is right for a two-word eyebrow over a
 * numeral and wrong for a five-word section label, which is the distinction the old
 * page did not draw. */
function Intro() {
  return (
    <div className="pt-space-11">
      <h1 className="max-w-[22ch] font-display text-display-lg font-extrabold text-content-primary">
        Every specimen on this page is the component.
      </h1>
      <p className="mt-space-7 max-w-[58ch] text-body-lg text-content-secondary">
        Not a picture of it, not a copy of its CSS. Each component has one recipe class that
        owns its variants, states and token bindings; the component renders from it and so does
        every table, grid and snippet below. The documentation cannot drift from the code because
        it is not a description of the code.
      </p>
      <dl className="mt-space-12 grid grid-cols-2 gap-x-space-6 gap-y-space-9 border-t-2 border-border-primary pt-space-8 sm:grid-cols-3 lg:grid-cols-5">
        {[
          [`${registry.size}`, 'components', 'each one recipe class'],
          [`${primitiveSummary.total}`, 'primitives', `${primitiveSummary.families} families, one palette`],
          [`${registry.tokenCoverage.length}`, 'tokens named', 'across every recipe'],
          [`${auditSummary.passing}/${auditSummary.gates}`, 'gates passing', 'measured by the build'],
          ['0', 'hex values', 'anywhere above tier 1'],
        ].map(([value, label, sub]) => (
          <div key={label}>
            <dt className="font-mono text-label-sm uppercase text-content-tertiary">
              {label}
            </dt>
            {/* tabular-nums so 655 and 188/188 sit on the same grid as 0 and 9. */}
            <dd className="mt-space-3 font-display text-display-sm font-extrabold tabular-nums text-content-primary">
              {value}
            </dd>
            <dd className="mt-space-2 max-w-[22ch] text-body-sm text-content-tertiary">{sub}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}

function Footer() {
  return (
    <footer className="mt-space-18 border-t-2 border-border-primary py-space-9">
      <p className="max-w-[74ch] text-body-md text-content-secondary">
        Values on this page come from <code className="font-mono">reports/audit.json</code> and{' '}
        <code className="font-mono">dist/tokens.css</code>, both regenerated by{' '}
        <code className="font-mono">node build/build.mjs</code>. To change a colour, change{' '}
        <code className="font-mono">build/spec.mjs</code> or{' '}
        <code className="font-mono">build/palette.mjs</code> and rebuild — editing anything under{' '}
        <code className="font-mono">dist/</code> or <code className="font-mono">tokens/</code> looks
        like it worked and vanishes on the next build.
      </p>
      <p className="mt-space-4 max-w-[74ch] text-body-sm text-content-tertiary">
        <a href="/verify" className="underline decoration-border-tertiary underline-offset-2 hover:text-content-primary">
          Verification
        </a>{' '}
        is the other half of this: every gate the build measures, and every token every recipe
        resolves to. This page shows what the tokens build into; that one shows they are correct.
        It replaced the standalone rig that used to live at{' '}
        <code className="font-mono">test/index.html</code> — see{' '}
        <code className="font-mono">archive/README.md</code> for why.
      </p>
    </footer>
  );
}

export function Showcase({ staleSources = [] }: { staleSources?: string[] }) {
  const entries = registry.all;

  /* Components are links now, not anchors. Each is its own route — see
   * ComponentPage.tsx for why the single scroll stopped working once the written
   * guidance landed. The rail still lists every one of them, because the list is how
   * somebody finds the one they want, and losing it to save a click would be the wrong
   * trade.
   *
   * That sentence read "all nine" while the catalogue held fourteen. The list is
   * `entries`, so it should never have carried a numeral at all — see the note in
   * ComponentPage.tsx for how far that particular figure spread before anyone counted. */
  /* One rail group per component family, rather than one flat list of every component.
   *
   * It was one flat list, and the list was in REGISTRATION order — which is the order the
   * components were built in. So Icon Button and Button Link sat tenth and eleventh instead of
   * beside Button, and the form controls added in one batch appeared before the three they
   * exist to sit with. Chronology is information about this repository, not about the system,
   * and at fourteen items it was merely odd; at thirty-four it was the only thing wrong with
   * the rail that a reader would actually notice.
   *
   * `registry.byGroup` supplies both the grouping and the ordering, and the index reads the
   * same accessor — two orderings of one catalogue is the drift the registry exists to
   * prevent, and it would surface as a rail whose sequence disagreed with the page under it.
   *
   * The count on each label is doing real work: `Forms 11` tells a first-time reader the shape
   * of the system in a way that thirty-four names in a column cannot. */
  const navGroups: NavGroup[] = [
    { label: 'foundations', items: FOUNDATION_SECTIONS },
    ...registry.byGroup.map(({ group, entries: inGroup }) => ({
      label: `${group.label} · ${inGroup.length}`,
      items: inGroup.map((e) => ({
        id: e.recipe.id,
        label: e.recipe.meta.title,
        href: `/c/${e.recipe.id}`,
      })),
    })),
    { label: 'in context', items: [{ id: 'assembled', label: 'Assembled' }] },
  ];

  /* Section numbering is derived, so inserting a component renumbers everything
   * after it without anyone maintaining a list of numbers. */
  const pad = (n: number) => String(n).padStart(2, '0');
  let n = 0;

  return (
    <ThemeProvider>
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:absolute focus:left-space-4 focus:top-space-4 focus:z-tooltip focus:rounded-4 focus:bg-fill-inverse focus:px-space-4 focus:py-space-3 focus:text-label-sm focus:text-content-on-inverse"
      >
        Skip to content
      </a>

      <Header staleSources={staleSources} />

      <div className="mx-auto grid max-w-container-xl grid-cols-1 gap-x-space-9 px-space-6 lg:grid-cols-rail">
        <NavRail groups={navGroups} />

        <main id="main" className="min-w-0 pb-space-18">
          <Intro />

          <Primitives index={pad(++n)} />
          <Foundations index={pad(++n)} />
          <Typography index={pad(++n)} />
          <Elevation index={pad(++n)} />
          <Spectrum index={pad(++n)} />

          {/* One index tile per component, each linking to its own route. This used to
              be one full ComponentSection per component, inline — ~150,000px of page
              once the guidance landed. (It said "nine full ComponentSections"; the
              earliest commit that has this file already registered fourteen, so the
              count was describing a catalogue that predates the history.) */}
          <ComponentIndex index={pad(++n)} />

          <Assembled index={pad(++n)} />
          <Footer />
        </main>
      </div>
    </ThemeProvider>
  );
}
